<a href="https://colab.research.google.com/github/domenicanarvaez-cmd/ALGEBRA/blob/main/Matriz_1_TAREA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np

# Definir dos matrices A y B de 3x3
A = np.array([[2, 4, 6],
              [1, 3, 5],
              [0, -1, 2]])

# Modificar la matriz B para que tenga las mismas dimensiones que A para suma y resta
B = np.array([[3,2, 1],
              [4, 0, -2],
              [1, 3, 5]])


print("Matriz A:\n", A)
print("\nMatriz B:\n", B)

# ------------------------------
# Suma de matrices
# ------------------------------

suma = A + B
print("\n Suma (A + B):\n", suma)

valors = A[1,1] + B[1,1]
print("El valor de C[1,1] es: ", valors)

# ------------------------------
#  Resta de matrices
# ------------------------------

resta = A - B
print("\n Resta (A - B):\n", resta)

valorr = A[0,2] - B[0,2]
print("El valor de C[0,2] es: ", valorr)

# ------------------------------
# Multiplicación por un escalar
# ------------------------------
escalar = 2
producto_escalar = escalar * A
print(f"\n Multiplicación por escalar ({escalar} * A):\n", producto_escalar)

valore = 2 * A[2,1]
print("El valor de 2A[2,1] es: ", valore)

# ------------------------------
#  Multiplicación matricial
# ------------------------------
producto = np.dot(A, B)   # o A @ B
print("\n Producto matricial (A * B):\n", producto)

valor = A[0,0]*B[0,0] + A[0,1]*B[1,0] + A[0,2]*B[2,0]
print("El valor de C[0,0] es: ", valor)

# ------------------------------
# Matriz transpuesta
# ------------------------------
#transpuesta = A.T
#print("\n Transpuesta de A (Aᵀ):\n", transpuesta)

Matriz A:
 [[ 2  4  6]
 [ 1  3  5]
 [ 0 -1  2]]

Matriz B:
 [[ 3  2  1]
 [ 4  0 -2]
 [ 1  3  5]]

 Suma (A + B):
 [[5 6 7]
 [5 3 3]
 [1 2 7]]
El valor de C[1,1] es:  3

 Resta (A - B):
 [[-1  2  5]
 [-3  3  7]
 [-1 -4 -3]]
El valor de C[0,2] es:  5

 Multiplicación por escalar (2 * A):
 [[ 4  8 12]
 [ 2  6 10]
 [ 0 -2  4]]
El valor de 2A[2,1] es:  -2

 Producto matricial (A * B):
 [[28 22 24]
 [20 17 20]
 [-2  6 12]]
El valor de C[0,0] es:  28


In [ ]:
from datetime import date

today = date.today()
print("Fecha actual:", today)

# Reemplaza "Tu Nombre" y "Tu Carrera" con tu información
nombres = "Domenica Brigeeth Narvaez Rivas"
carrera = "Ingienería en Computación"

print("Nombre:", nombres)
print("Carrera:", carrera)

Fecha actual: 2025-10-20
Nombre: Domenica Brigeeth Narvaez Rivas
Carrera: Ingienería en Computación
